import { chromium } from "playwright";
const b = await chromium.launch();
const p = await b.newPage({ viewport: { width: 390, height: 900 }, deviceScaleFactor: 2 });
await p.goto("http://localhost:5173/", { waitUntil: "networkidle" });
await p.waitForTimeout(2200);
await p.getByText("Explore with the demo account").click();
await p.waitForTimeout(4500);
const pulse = await p.getByText("Agent Pulse").count();
console.log("Agent Pulse visible on Home:", pulse > 0);
await p.evaluate(() => document.querySelector("main").scrollTo?.(0, 0));
await p.screenshot({ path: "/home/user/shots/pulse-home.png" });
await p.goto("http://localhost:5173/agent", { waitUntil: "networkidle" });
await p.waitForTimeout(3500);
console.log("Agent Pulse visible on Agent:", await p.getByText("Agent Pulse").count() > 0);
await p.evaluate(() => window.scrollTo(0, 260));
await p.waitForTimeout(400);
await p.screenshot({ path: "/home/user/shots/pulse-agent.png" });
await b.close();
