headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[functions]

[functions."*"]

[build]
publish = "/home/user/forexmind-ai/frontend/dist"
publishOrigin = "config"
commandOrigin = "config"
base = "/home/user/forexmind-ai/frontend"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[[headers]]
for = "/manifest.webmanifest"

[headers.values]
Content-Type = "application/manifest+json"

[[headers]]
for = "/*"

[headers.values]
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"

[[redirects]]
from = "/api/*"
to = "https://forexmind-ai-api.onrender.com/api/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/api/*"
to = "https://forexmind-ai-api.onrender.com/api/:splat"
status = 200.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/index.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]